# Site settings
title: 爱吃汤圆的波波茶
email: roynbo@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
 波神的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://roynbo.github.io/" # the base hostname & protocol for your site

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag' 


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username
github: roynbo

# Comment
# disqus_shortname: discussion_shortname

# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
